name: changeln
base: core18
version: '1.0.6'
summary: Generate changelog from git tags
description: |
  Generate markdown, html, pdf. Grouping by regular expression. Parsing one comment to multiplicity. Template engine (Mako)
grade: stable
confinement: strict

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /var/cache/fontconfig:
    bind: $SNAP_DATA/var/cache/fontconfig

parts:
  changeln:
    plugin: python
    python-version: python3
    source: .
    python-packages:
      - click
      - Mako
      - pyYaml
      - gitpython
      - natsort
      - Markdown
      - WeasyPrint
      - setuptools
    stage-packages:
      - git
      - fonts-freefont-ttf
      - fonts-arphic-uming
      - fontconfig-config

  changeln-run:
    plugin: dump
    source: scripts
    organize:
      run.sh: bin/

apps:
  changeln:
    command: bin/run.sh
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    extensions:
      - gnome-3-34
    plugs:
      - home